- hosts: all
  remote_user: root
  vars_files:
    - ../vars/main.yml
    - ../vault/db.yml
    - ../vault/django.yml
  vars:
    project_dir: "/var/www/2photo-api"
    virtualenv_dir: "{{ project_dir }}/.env"
    local_settings_path: "{{ project_dir }}/two_photo_api/local_settings.py"
    local_settings_template: "../templates/local_settings.py"
    requirements_file: "{{ project_dir }}/requirements.pip"
    repo_url: "https://github.com/petropavel13/2photo-api"
    nginx_site_conf_src_path: "{{ project_dir }}/two_photo_api/nginx.conf"
    nginx_site_conf_dest_path: "/etc/nginx/sites-available/2photo-api"
  tasks:
    - name: Install essential packages
      apt: name={{ item }}
      with_items:
        - python-pip
        - git
        - nginx
    - name: Install virtualenv
      pip: name=virtualenv
    - name: Create project folder
      file: path={{ project_dir }} state=directory owner="www-data" group="www-data"
    - name: Clone repo
      git: repo={{ repo_url }} dest={{ project_dir }}
      sudo: yes
      sudo_user: www-data
    - name: Create virtualenv
      command: "virtualenv {{ virtualenv_dir }}"
      sudo: yes
      sudo_user: www-data
    - name: Install dev packages
      apt: name={{ item }}
      with_items:
        - libcurl4-openssl-dev
        - "postgresql-server-dev-{{ pg_version }}"
        - python-dev
        - libxml2-dev
        - libxslt1-dev
    - name: Install pip requirements
      pip: virtualenv={{ virtualenv_dir }} requirements={{ requirements_file }} extra_args="--no-cache-dir"
      sudo: yes
      sudo_user: www-data
    - name: Create local settings
      template: src={{ local_settings_template }} dest={{ local_settings_path }}
      sudo: yes
      sudo_user: www-data
    - name: Link nginx configuration
      file: src={{ nginx_site_conf_src_path }} dest={{ nginx_site_conf_dest_path }} state=link
